# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook

PreCommit:
  TrailingWhitespace:
    enabled: true

PostCheckout:
  ReStow:
    enabled: true
    description: 'Re-stow all files'
    required_executable: 'stow'

BundleInstall:
    enabled: true

BundleCheck:
    enabled: true
