#!/usr/bin/env zsh

# The zvm_after_init_commands array is a hook provided by the zsh-vi-mode plugin.
#
# It is used to execute commands after the vi-mode initialization is complete. This
# is necessary because zsh-vi-mode often overwrites or interferes with keybindings
# and widgets from other plugins (like atuin or zsh-autosuggestions) during its setup.
zvm_after_init_commands+=('[ -f ~/.zsh_profile.d/atuin ] && source ~/.zsh_profile.d/atuin')
