#!/usr/bin/env zsh

if type brew > /dev/null 2>&1; then
  source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
  source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

zvm_after_init_commands+=('[ -f ~/.zsh_profile.d/atuin ] && source ~/.zsh_profile.d/atuin')
