#!/usr/bin/env bash

# select account; then print and copy code to clipboard
# arguments get passed to fzf as query
function totp {
  if [ "$(bw status | jq --raw-output .status)" != unlocked ]; then
    echo 'Need to login; use export BW_SESSION="$(bw unlock --raw)"'
  else
    bw list items  | jq -r '.[] | select(.login.totp) | .name' | fzf-tmux --query "$@" | xargs -I ACCT bw get totp ACCT | tee /dev/stderr | pbcopy
  fi
}
