FROM docker.io/debian:trixie-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      git \
      locales \
      stow \
      zsh \
 && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
 && locale-gen \
 && rm -rf /var/lib/apt/lists/*

RUN chsh -s /usr/bin/zsh

WORKDIR /root

# Testing the dotfiles repo directory
ADD . .dotfiles

# Alternatively, we can also test the published main branch
# RUN git clone https://github.com/suhlig/dotfiles.git .dotfiles

RUN cd /root/.dotfiles && ./bootstrap.zsh

WORKDIR /root
CMD ["zsh"]
