FROM docker.io/debian:trixie-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      git \
      locales \
      stow \
      zsh \
 && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
 && locale-gen \
 && rm -rf /var/lib/apt/lists/*

# Testing the current work directory
WORKDIR /root
ADD . .dotfiles

# Alternatively, we can test the published main branch
# RUN git clone https://github.com/suhlig/dotfiles.git ~/.dotfiles

RUN cd ~/.dotfiles && ./bootstrap.zsh

RUN chsh -s /usr/bin/zsh

CMD ["zsh"]
