FROM dotfiles-debian-trixie:slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      curl \
      starship \
      tmux \
 && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
RUN curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
RUN git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# TODO Once tpm was installed, press `<prefix>I` to install all plugins.

RUN cd ~/.dotfiles && ./bootstrap.zsh
