matches:
  - trigger: "now#"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y %H:%M Uhr"
  - trigger: "date#"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "ts#"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S"
  - trigger: "unix#"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%s"
  - trigger: "gonow#"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "time.Date(%Y, %m, %d, %H, %M, %S, 0, time.Local"
  - trigger: "bd#"
    replace: 71149 Bondorf
  - trigger: "bic#"
    replace: CSDBDE71
  - trigger: "handy#"
    replace: +49 151 2535 0419
  - trigger: "home#"
    replace: +49 7457 948100
  - trigger: "iban#"
    replace: DE89760300800210122228
  - trigger: "noris#"
    replace: DE63100777770778018200
  - trigger: "kmst#"
    replace: Karl-Marx-Stadt
  - trigger: "mfg#"
    replace: |
      Mit freundlichen Grüßen

      Steffen Uhlig
  - trigger: pry!
    replace: |
      require 'pry'
      binding.pry
  - trigger: irb!
    replace: |
      require 'irb'
      binding.irb
  - trigger: "raspi#"
    replace: Raspberry Pi
  - trigger: "rw#"
    replace: Reutiner Weg 3
  - trigger: "su#"
    replace: Steffen Uhlig
  - trigger: "visa#"
    replace: 4159321004347028
  - trigger: "@ibm"
    replace: Steffen.Uhlig@de.ibm.com
  - trigger: "@uh"
    replace: steffen@familie-uhlig.net
  - trigger: "strict#"
    replace: |
      #!/bin/bash

      set -euo pipefail
      IFS=$'\n\t'
  - trigger: "bw#"
    replace: Baden-Württemberg
  - trigger: sgduh
    replace: |
      Sehr geehrte Damen und Herren,
  - trigger: "cmd#"
    replace: |
      ```command
      $ $|$
      ```
  - trigger: "rq#"
    replace: "require '$|$'"
  - trigger: "abbr#"
    replace: "<abbr title=\"\"$|$\"\"></abbr>"
  - trigger: "link#"
    replace: "[]({{clipboard}})"
  - trigger: "up#"
    replace: "up -c \"jq -r '.'\""
  - trigger: "dlv#"
    replace: "dlv debug --headless --log --api-version 2 --listen localhost:2345 ."
  - trigger: "maine#"
    replace: "package main\n\nimport (\n  \"fmt\"\n  \"os\"\n)\n\nfunc main() {\n  err := mainE()\n\n  if err != nil {\n    fmt.Fprintf(os.Stderr, \"Error %s\\n\", err)\n    os.Exit(1)\n  }\n}\n\nfunc mainE() error {\n  return nil\n}\n"
  - trigger: fperr
    replace: |
      fmt.Fprintf(os.Stderr, "%s\n", )
  - trigger: v11y
    replace: vulnerability
  - trigger: v13s
    replace: vulnerabilities
  - trigger: s6y
    replace: severity
  - trigger: s8s
    replace: severities
