enable_experimental_conpty_backend = false
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x5D5D5D"
blue = "0x9CD9F0"
cyan = "0x77DFD8"
green = "0xCDEE69"
magenta = "0xFBB1F9"
red = "0xE09690"
white = "0xF7F7F7"
yellow = "0xFFE377"

[colors.normal]
black = "0x000000"
blue = "0x4E90A7"
cyan = "0x218693"
green = "0x8EB33B"
magenta = "0xC8A0D1"
red = "0xC75646"
white = "0xB0B0B0"
yellow = "0xD0B03C"

[colors.primary]
background = "0x232423"
bright_foreground = "0xfeffff"
foreground = "0xF8F8F8"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
persistent_logging = false
render_timer = false

[font]
size = 14.0

[font.bold]
family = "Roboto Mono for Powerline"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Roboto Mono for Powerline"
style = "Italic"

[font.normal]
family = "Roboto Mono Light for Powerline"
style = "Light"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
