brew "chruby"
brew "curl"
brew "direnv"
brew "fasd"
brew "git"
brew "graphviz"
brew "htop"
brew "libxml2"
brew "ruby-install"
brew "the_silver_searcher" # ag
brew "openssh"
brew "ripgrep"
brew "stow"
brew "task"
brew "tmux"
brew "vim"
brew "zsh"

tap "git-duet/tap"
brew "git-duet/tap/git-duet"

# TODO Needs update for Linux
# tap "jthomas/tools"
# brew "wsk"

tap "cloudfoundry/tap"
brew "cf-cli"
brew "bosh-cli"
