#!/usr/bin/env bash
set -e

task-rest(){
  if [ -z "$1" ]; then
    echo "No task id supplied"
    exit 1
  fi
  
  local task_id="$1"
  shift
  local reason="${*}"
  
  if [ -z "$reason" ]; then
    reason="No longer applicable"
  fi
    
  task "$task_id" annot "$reason"
  task "$task_id" done
}

